apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmcluster
  namespace: victoriametrics
spec:
  interval: 10m
  chart:
    spec:
      chart: vm/victoria-metrics-cluster
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
        namespace: victoriametrics
      interval: 10m
  values:
    vmselect:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8481"

    vminsert:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8480"

    vmstorage:
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8482"


