apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoriametrics
  namespace: victoriametrics
spec:
  nodeSelector:
    kubernetes.io/hostname: k3s-mntr-*
  interval: 1m
  url: https://victoriametrics.github.io/helm-charts/

