---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: galera
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./app/mariadb-operator/galera"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 3m
  dependsOn:
    - name: mariadb-operator
