---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - alert.yaml
  - provider.yaml
  - secrets-encrypt.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alerts
  namespace: flux-system
spec:
  interval: 5m0s
  path: .
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: alerts
  wait: true
  timeout: 3m
  dependsOn:
    - name: sealed-secrets
