apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  nodeSelector:
    kubernetes.io/hostname: k3s-mntr-*
  interval: 1m
  url: https://grafana.github.io/helm-charts

