apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-monitoring
  namespace: default
spec:
  interval: 5m
  path: "./clusters/mntr"
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  prune: true
  kubeConfig:
    secretRef:
      name: monitoring-kubeconfig
  dependsOn:
    - name: capi-clusters
      namespace: flux-system
