apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-monitoring
  namespace: monitoring
spec:
  interval: 5m
  path: "./clusters/mntr"
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  kubeConfig:
    secretRef:
      name: monitoring-kubeconfig
