apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wordpress
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb-galera
    namespace: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: "wordpress"
  table: "*"
  username: wordpress
  grantOption: true
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
