apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: wordpress
  namespace: wordpress
spec:
  mariaDbRef:
    name: mariadb-galera
  passwordSecretKeyRef:
    name: wordpress-password
    key: password
  maxUserConnections: 10
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 30s
  retryInterval: 5s
