kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: app
networking:
  podSubnet: "10.42.0.0/16"
  serviceSubnet: "10.52.0.0/16"
  disableDefaultCNI: true
nodes:
  - role: control-plane
  - role: worker
  - role: worker
