kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mgmt
networking:
  podSubnet: "10.44.0.0/16"
  serviceSubnet: "10.54.0.0/16"
  disableDefaultCNI: true
nodes:
  - role: control-plane
  - role: worker
