kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: mntr
networking:
  podSubnet: "10.43.0.0/16"
  serviceSubnet: "10.53.0.0/16"
  disableDefaultCNI: true
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
