apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium-release
  namespace: cilium
spec:
  values:
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: "10.0.0.0/16"

