---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victorialogs
  namespace: flux-system
  labels:
    app.kubernetes.io/sops: enabled
spec:
  interval: 5m0s
  path: "./apps/monitoring/victorialogs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 3m
