apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: mariadb-galera-backup
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb-galera
  maxRetention: 720h
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce
  schedule:
    cron: "0 * * * *"
    suspend: false
  timeZone: "Europe/Paris"
  compression: gzip
