---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 5m0s
  path: "/app/sealed-secrets"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: sealed-secrets
  wait: true
  timeout: 3m
