apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vmlogs
  namespace: victorialogs
spec:
  nodeSelector:
    kubernetes.io/hostname: k3s-mntr-*
  interval: 1m
  chart:
    spec:
      chart: victoria-logs-single
      sourceRef:
        kind: HelmRepository
        name: victorialogs
        namespace: victorialogs
      interval: 1m
  values:
    vector:
      enabled: true
