apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: capi-release
  namespace: capi
spec:
  interval: 1m
  chart:
    spec:
      chart: cluster-api-operator
      sourceRef:
        kind: HelmRepository
        name: capi-repo
        namespace: capi
      interval: 1m
  values:
    infrastructure:
      docker:
        createNamespace: true
    manager:
      featureGates:
        core:
          ClusterTopology: true
        docker:
          ClusterTopology: true
