apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium
  namespace: app
spec:
  valuesTemplate: |
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: "10.100.0.0/16"

