apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium
  namespace: capi-system
spec:
  clusterSelector:
    matchLabels:
      cilium: enabled
  repoURL: https://helm.cilium.io
  chartName: cilium
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
    install:
      createNamespace: true
  valuesTemplate: |
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: "0.0.0.0/16"
