apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium-release
  namespace: cilium
spec:
  interval: 1m
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium-repo
        namespace: cilium
      interval: 1m
  values:
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList: "0.0.0.0/16"
