apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capi-clusters-release
  namespace: capi-system
spec:
  chart:
    spec:
      chart: ./charts/capi-clusters
      sourceRef:
        kind: GitRepository
        name: capi-clusters-repo
        namespace: capi-system
  interval: 1m
