apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: capi-clusters-release
  namespace: capi-system
spec:
  chart:
    spec:
      chart: ./charts/capi-clusters
      sourceRef:
        kind: GitRepository
        name: capi-clusters-repo
        namespace: capi-system
  interval: 1m
  values:
    clusters:
      - name: monitoring
        kubernetes:
          version: "v1.33.0"
        replicas:
          cp: 1
          worker: 3
        network:
          podCidr: "10.0.0.0/16"
          svcDomain: "cluster.local"
          svcCidr: "10.10.0.0/16"

      - name: app
        kubernetes:
          version: "v1.33.0"
        replicas:
          cp: 1
          worker: 3
        network:
          podCidr: "10.100.0.0/16"
          svcDomain: "cluster.local"
          svcCidr: "10.110.0.0/16"

      - name: nginx
        kubernetes:
          version: "v1.33.0"
        replicas:
          cp: 1
          worker: 3
        network:
          podCidr: "10.200.0.0/16"
          svcDomain: "cluster.local"
          svcCidr: "10.210.0.0/16"
