apiVersion: v1
kind: Service
metadata:
  name: source-controller-metrics
  namespace: flux-system
spec:
  ports:
  - name: http-prom
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: source-controller
  type: ClusterIP
