apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - {{ .Values.network.podCidr }}
    serviceDomain: {{ .Values.network.svcDomain }}
    services:
      cidrBlocks:
      - {{ .Values.network.svcCidr }}
  topology:
    class: quick-start
    controlPlane:
      metadata: {}
      replicas: {{ .Values.replicas.cp }}
    variables:
    - name: imageRepository
      value: ""
    - name: etcdImageTag
      value: ""
    - name: coreDNSImageTag
      value: ""
    - name: podSecurityStandard
      value:
        audit: restricted
        enabled: true
        enforce: baseline
        warn: restricted
    version: {{ .Values.kubernetes.version }}
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: {{ .Values.replicas.worker }}
