apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-state-metrics
      sourceRef:
        kind: HelmRepository
        name: kube-state-metrics
        namespace: kube-state-metrics
      interval: 1m
