apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-state-metrics
  namespace: kube-state-metrics
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts

