apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-exporter
  namespace: node-exporter
spec:
  interval: 1m
  chart:
    spec:
      chart: node-exporter
      sourceRef:
        kind: HelmRepository
        name: node-exporter
        namespace: node-exporter
      interval: 1m
