apiVersion: v1
kind: Secret
metadata:
    name: test-password
    namespace: mariadb
type: Opaque
data:
    password: ENC[AES256_GCM,data:4fXdcz19nCaB99Bw,iv:MCBKHNjuu0f9mkrI912y3xblnqi4r9Wl7euysEYbcHU=,tag:oBEXbmf9sYauftoBBY9DJQ==,type:str]
sops:
    age:
        - recipient: age1jfe5kqwryq0s4c97wknnnve0nwg3rs2wqh6pgu5v26m8vch4ldlqaxmddq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaitqR2F0NDVJYmUxSDUx
            VWppcG5jK3ZGWnZQQnlpZlNkcnA0VExsM0g4Ck1Ec2xVdU9sUDZDaGNqKzZyRGNv
            cVBYdmZxTlFyak5XbFVRZEI4eVNoR0EKLS0tIHBGSm4zQTFCZ0p1SDJkSDE3dkd0
            RzhtWkRldUV6RDNhQjBMaE5OMFRoalkKB0/95ONzBz7LGf3/SeuRZ72xaCqI4FLI
            HkgcFB+ZP0JoS74CA9cPduOD2/OdoiKP5U5N/KOVVA/P/dJIKKsObQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T20:59:55Z"
    mac: ENC[AES256_GCM,data:oQeoAFK8mgM8UQaaBcKJ2oJThKSH84LNhvcxv5wMngO9sF3INOXnwd9SuFoe1J/UY6bJGKaKAPyD+nm3Umd6+M75Mo3RhARyX8rbsQMiGzxKOVVpF9gdlRF87+daoWKQ9PawgYr5LoWs2xEBzCez3+nO3/HGEd8L29GRULScsTY=,iv:whmKQ4DioHHkL5E31wnU3ytjKEE9Zo+2ccgIhMqLdZg=,tag:abH8sICqP9bEYz96OXpIXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: root-password
    namespace: mariadb
type: Opaque
data:
    password: ENC[AES256_GCM,data:j4m6hERTatvPh4Xu,iv:5KLgqmv+HHs9YU++E4dAnpUERXRVzdKk4Nj59o5B4Rw=,tag:xfRZWvqZ43Y9gQ5rtw53Uw==,type:str]
sops:
    age:
        - recipient: age1jfe5kqwryq0s4c97wknnnve0nwg3rs2wqh6pgu5v26m8vch4ldlqaxmddq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaitqR2F0NDVJYmUxSDUx
            VWppcG5jK3ZGWnZQQnlpZlNkcnA0VExsM0g4Ck1Ec2xVdU9sUDZDaGNqKzZyRGNv
            cVBYdmZxTlFyak5XbFVRZEI4eVNoR0EKLS0tIHBGSm4zQTFCZ0p1SDJkSDE3dkd0
            RzhtWkRldUV6RDNhQjBMaE5OMFRoalkKB0/95ONzBz7LGf3/SeuRZ72xaCqI4FLI
            HkgcFB+ZP0JoS74CA9cPduOD2/OdoiKP5U5N/KOVVA/P/dJIKKsObQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T20:59:55Z"
    mac: ENC[AES256_GCM,data:oQeoAFK8mgM8UQaaBcKJ2oJThKSH84LNhvcxv5wMngO9sF3INOXnwd9SuFoe1J/UY6bJGKaKAPyD+nm3Umd6+M75Mo3RhARyX8rbsQMiGzxKOVVpF9gdlRF87+daoWKQ9PawgYr5LoWs2xEBzCez3+nO3/HGEd8L29GRULScsTY=,iv:whmKQ4DioHHkL5E31wnU3ytjKEE9Zo+2ccgIhMqLdZg=,tag:abH8sICqP9bEYz96OXpIXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
