apiVersion: v1
kind: Secret
metadata:
  name: test-password
  namespace: mariadb
type: Opaque
data:
  password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: root-password
  namespace: mariadb
type: Opaque
data:
  password: cGFzc3dvcmQ=
