apiVersion: k8s.mariadb.com/v1alpha1
kind: SqlJob
metadata:
  name: create-table
  namespace: mariadb
spec:
  mariaDbRef:
    name: mariadb-galera
  username: test
  passwordSecretKeyRef:
    name: test-password
    key: password
  database: test
  sql: |
    CREATE TABLE IF NOT EXISTS toto (colonne1 int);
    INSERT INTO toto (colonne1) VALUES (1);
